spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    show-sql: false

server:
  forward-headers-strategy: framework   # respect Render's proxy headers

management:
  endpoint:
    health:
      show-details: never

logging:
  level:
    root: INFO
    com.protrack: INFO
