-- ============================================================================
-- Protrack — V2 identity foundation
-- ----------------------------------------------------------------------------
-- Identity & Access tables per the approved Database Design:
--   organizations (tenancy root) · users · roles · permissions ·
--   user_roles · role_permissions
--
-- Conventions (approved): UUID for exposed entities (organizations, users) —
-- generated in the app layer (UUID v7); INT identity for reference tables
-- (roles, permissions). Enums stored as VARCHAR + CHECK. Audit columns on
-- mutable tables. No JWT / Spring Security / auth logic in this migration.
-- ============================================================================

-- ── Organizations: tenancy root (single-tenant in Phase 1; one seeded org) ──
CREATE TABLE organizations (
    id         UUID PRIMARY KEY,
    name       VARCHAR(160) NOT NULL,
    slug       VARCHAR(80)  NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_organizations_slug UNIQUE (slug)
);

-- ── Roles: reference table (fixed set) ──
CREATE TABLE roles (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(40)  NOT NULL,
    name        VARCHAR(80)  NOT NULL,
    description VARCHAR(255),
    CONSTRAINT uq_roles_code UNIQUE (code)
);

-- ── Permissions: reference table (populated as fine-grained RBAC is defined) ──
CREATE TABLE permissions (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(80) NOT NULL,
    description VARCHAR(255),
    CONSTRAINT uq_permissions_code UNIQUE (code)
);

-- ── Users: platform accounts ──
CREATE TABLE users (
    id              UUID PRIMARY KEY,
    organization_id UUID         NOT NULL,
    email           VARCHAR(255) NOT NULL,
    password_hash   VARCHAR(100) NOT NULL,
    full_name       VARCHAR(160) NOT NULL,
    avatar_initials VARCHAR(4),
    avatar_color    VARCHAR(16),
    status          VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    last_login_at   TIMESTAMPTZ,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by      UUID,
    updated_by      UUID,
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT fk_users_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED'))
);
CREATE INDEX ix_users_organization ON users (organization_id);

-- ── user_roles: M:N users <-> roles ──
CREATE TABLE user_roles (
    user_id     UUID        NOT NULL,
    role_id     INT         NOT NULL,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    assigned_by UUID,
    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE RESTRICT
);
CREATE INDEX ix_user_roles_role ON user_roles (role_id);

-- ── role_permissions: M:N roles <-> permissions ──
CREATE TABLE role_permissions (
    role_id       INT NOT NULL,
    permission_id INT NOT NULL,
    CONSTRAINT pk_role_permissions PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_role_permissions_role FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE,
    CONSTRAINT fk_role_permissions_permission FOREIGN KEY (permission_id) REFERENCES permissions (id) ON DELETE CASCADE
);
CREATE INDEX ix_role_permissions_permission ON role_permissions (permission_id);

-- ============================================================================
-- Seed data
-- ============================================================================

-- Default organization (tenancy root).
INSERT INTO organizations (id, name, slug)
VALUES (gen_random_uuid(), 'Protrack', 'protrack');

-- Four fixed roles.
INSERT INTO roles (code, name, description) VALUES
    ('ADMIN',    'Administrator',      'Manages users, roles, imprints, the audit log, reports and settings.'),
    ('PM',       'Project Manager',    'Creates projects, uploads manuscripts, oversees the pipeline and team.'),
    ('DESIGNER', 'Production Designer', 'Downloads the production package, lays out offline in InDesign, uploads the PDF.'),
    ('QA',       'QA Engineer',        'Reviews AI preflight, resolves issues, approves and applies the e-signature.');

-- One demo user per role. Names/emails are placeholder sample data.
-- Demo password for all four is "password"; password_hash is a BCrypt(cost 10) hash of it
-- (Spring's BCryptPasswordEncoder verifies the $2b$ prefix). Real auth lands in Task 1.2.
INSERT INTO users (id, organization_id, email, password_hash, full_name, avatar_initials, avatar_color)
SELECT gen_random_uuid(), o.id, v.email,
       '$2b$10$fEa0UTsrJtEDoUWgy7ORHOntDSlbM2YddeSjUC2v/ID5TiOaLIgJG',
       v.full_name, v.initials, v.color
FROM organizations o
CROSS JOIN (VALUES
    ('priya.anand@protrack.io', 'Priya Anand', 'PA', '#0B63CE'),
    ('marcus.reed@protrack.io', 'Marcus Reed', 'MR', '#1F9D57'),
    ('lena.ortiz@protrack.io',  'Lena Ortiz',  'LO', '#C9821A'),
    ('david.cho@protrack.io',   'David Cho',   'DC', '#6D5EF0')
) AS v(email, full_name, initials, color)
WHERE o.slug = 'protrack';

-- Assign each demo user its role.
INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id
FROM users u
JOIN (VALUES
    ('priya.anand@protrack.io', 'PM'),
    ('marcus.reed@protrack.io', 'DESIGNER'),
    ('lena.ortiz@protrack.io',  'QA'),
    ('david.cho@protrack.io',   'ADMIN')
) AS m(email, role_code) ON m.email = u.email
JOIN roles r ON r.code = m.role_code;
