-- ============================================================================
-- Protrack — V4 projects & workflow
-- ----------------------------------------------------------------------------
-- Project lifecycle backbone per the approved Database Design:
--   imprints · workflow_stages · projects · project_members · project_stage_history
--
-- Conventions (approved): UUID PK for exposed entities (app-generated v7; seeds use
-- gen_random_uuid()); INT identity PK for reference tables (workflow_stages); enums as
-- VARCHAR + CHECK; audit columns on mutable tables; confidence/score values 0–100.
-- No entities/services/APIs in this task — schema only.
-- ============================================================================

-- ── Imprints: a publishing imprint within an organization ──
CREATE TABLE imprints (
    id              UUID PRIMARY KEY,
    organization_id UUID         NOT NULL,
    name            VARCHAR(160) NOT NULL,
    code            VARCHAR(80)  NOT NULL,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_imprints_code UNIQUE (code),
    CONSTRAINT fk_imprints_organization FOREIGN KEY (organization_id) REFERENCES organizations (id)
);
CREATE INDEX ix_imprints_organization ON imprints (organization_id);

-- ── Workflow stages: the canonical pipeline (reference table) ──
CREATE TABLE workflow_stages (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(40)  NOT NULL,
    name        VARCHAR(80)  NOT NULL,
    sequence    INT          NOT NULL,
    description VARCHAR(255),
    CONSTRAINT uq_workflow_stages_code UNIQUE (code),
    CONSTRAINT uq_workflow_stages_sequence UNIQUE (sequence)
);

-- ── Projects: the central aggregate ──
CREATE TABLE projects (
    id               UUID PRIMARY KEY,
    organization_id  UUID         NOT NULL,
    imprint_id       UUID,
    owner_id         UUID,
    title            VARCHAR(250) NOT NULL,
    isbn             VARCHAR(32),
    publication_type VARCHAR(40)  NOT NULL,
    discipline       VARCHAR(120),
    brief            TEXT,
    page_extent      INT,
    trim_size        VARCHAR(40),
    priority         VARCHAR(20)  NOT NULL DEFAULT 'MEDIUM',
    current_stage    VARCHAR(40)  NOT NULL DEFAULT 'INTAKE',
    status           VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    due_date         DATE,
    created_date     DATE         NOT NULL DEFAULT CURRENT_DATE,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by       UUID,
    updated_by       UUID,
    deleted_at       TIMESTAMPTZ,
    CONSTRAINT fk_projects_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_projects_imprint FOREIGN KEY (imprint_id) REFERENCES imprints (id),
    CONSTRAINT fk_projects_owner FOREIGN KEY (owner_id) REFERENCES users (id),
    CONSTRAINT fk_projects_current_stage FOREIGN KEY (current_stage) REFERENCES workflow_stages (code),
    CONSTRAINT ck_projects_publication_type CHECK (publication_type IN
        ('STEM_TEXTBOOK', 'MONOGRAPH', 'JOURNAL', 'REFERENCE')),
    CONSTRAINT ck_projects_priority CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH')),
    CONSTRAINT ck_projects_status CHECK (status IN ('ACTIVE', 'ON_HOLD', 'COMPLETED', 'ARCHIVED')),
    CONSTRAINT ck_projects_page_extent CHECK (page_extent IS NULL OR page_extent > 0)
);
CREATE INDEX ix_projects_org_stage ON projects (organization_id, current_stage);
CREATE INDEX ix_projects_owner ON projects (owner_id);
CREATE INDEX ix_projects_imprint ON projects (imprint_id);
CREATE INDEX ix_projects_due_date ON projects (due_date);
CREATE INDEX ix_projects_status ON projects (status) WHERE deleted_at IS NULL;

-- ── Project members: staffing (M:N project <-> user, with AI match score) ──
CREATE TABLE project_members (
    id              UUID PRIMARY KEY,
    project_id      UUID         NOT NULL,
    user_id         UUID         NOT NULL,
    role_in_project VARCHAR(40),
    is_owner        BOOLEAN      NOT NULL DEFAULT FALSE,
    match_score     NUMERIC(5, 2),
    assigned_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    assigned_by     UUID,
    CONSTRAINT uq_project_members_project_user UNIQUE (project_id, user_id),
    CONSTRAINT fk_project_members_project FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,
    CONSTRAINT fk_project_members_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_project_members_assigned_by FOREIGN KEY (assigned_by) REFERENCES users (id),
    CONSTRAINT ck_project_members_match_score CHECK (match_score IS NULL OR (match_score >= 0 AND match_score <= 100))
);
CREATE INDEX ix_project_members_user ON project_members (user_id);

-- ── Project stage history: append-only transition log (immutable snapshot) ──
CREATE TABLE project_stage_history (
    id             UUID PRIMARY KEY,
    project_id     UUID         NOT NULL,
    from_stage     VARCHAR(40),
    to_stage       VARCHAR(40)  NOT NULL,
    triggered_role VARCHAR(40),
    triggered_by   UUID,
    note           TEXT,
    occurred_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_project_stage_history_project FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,
    CONSTRAINT fk_project_stage_history_triggered_by FOREIGN KEY (triggered_by) REFERENCES users (id)
);
CREATE INDEX ix_project_stage_history_project ON project_stage_history (project_id, occurred_at DESC);

-- ============================================================================
-- Seed data
-- ============================================================================

-- Canonical 7-stage pipeline (sequence drives ordering in the UI).
INSERT INTO workflow_stages (code, name, sequence, description) VALUES
    ('INTAKE',        'Intake',       1, 'Project created and manuscript uploaded.'),
    ('AI_ANALYSIS',   'AI Analysis',  2, 'AI extracts structure and scores readiness; PM reviews.'),
    ('DESIGN_PREP',   'Design Prep',  3, 'Production assets prepared and handed off to the designer.'),
    ('IN_PRODUCTION', 'In Production', 4, 'Designer lays out pages offline in Adobe InDesign.'),
    ('PDF_REVIEW',    'PDF Review',   5, 'Uploaded PDF runs through AI preflight.'),
    ('QA_SIGNOFF',    'QA Sign-off',  6, 'QA resolves issues, approves and e-signs.'),
    ('COMPLETED',     'Completed',    7, 'Approved, sealed and archived with a full audit record.');

-- One default imprint under the seeded organization.
INSERT INTO imprints (id, organization_id, name, code)
SELECT gen_random_uuid(), o.id, 'Physical Sciences', 'PHYSICAL_SCIENCES'
FROM organizations o
WHERE o.slug = 'protrack';
